# Generated by Django 5.1.6 on 2025-04-04 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='aboutcompany',
            new_name='About_company',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='location',
            new_name='Location',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='type',
            new_name='Type',
        ),
        migrations.RemoveField(
            model_name='company',
            name='date_time',
        ),
    ]
