# Generated by Django 5.1.6 on 2025-04-04 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_aboutcompany_company_about_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='Name',
            new_name='company_Name',
        ),
    ]
