# Generated by Django 5.1.6 on 2025-04-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_name_company_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
