# Generated by Django 5.1.6 on 2025-04-08 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_company_active_company_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('address', models.TextField(max_length=100)),
                ('phone_no', models.CharField(max_length=10)),
                ('about', models.CharField(max_length=100)),
                ('Employee_position', models.CharField(choices=[('HR', 'HR'), ('Manager', 'Manager'), ('leader', 'leader')], max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
        ),
    ]
